#!/bin/bash
# Firebase Setup & Deployment Guide
# Run this as a reference checklist

echo "═══════════════════════════════════════════════════════════════"
echo "  FIREBASE BACKEND - SETUP & DEPLOYMENT GUIDE"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "📋 STEP 1: ENVIRONMENT SETUP"
echo "─────────────────────────────────────────────────────────────"
echo "  1. Copy environment template:"
echo "     cp .env.example .env.local"
echo ""
echo "  2. Edit .env.local with your Firebase credentials:"
echo "     VITE_FIREBASE_API_KEY=..."
echo "     VITE_FIREBASE_PROJECT_ID=..."
echo "     (Get values from Firebase Console > Project Settings)"
echo ""
echo "  3. Restart dev server for changes to take effect"
echo ""

echo "🔐 STEP 2: DEPLOY SECURITY RULES"
echo "─────────────────────────────────────────────────────────────"
echo "  1. Open Firebase Console"
echo "     https://console.firebase.google.com"
echo ""
echo "  2. Select your project > Firestore Database > Rules tab"
echo ""
echo "  3. Copy-paste content from:"
echo "     src/firebase/firebaseRules.txt"
echo ""
echo "  4. Click Publish"
echo ""
echo "  ✅ Rules deployed! Users can now read/write securely"
echo ""

echo "🔧 STEP 3: CREATE COMPOSITE INDEXES (Optional)"
echo "─────────────────────────────────────────────────────────────"
echo "  Firestore will auto-suggest indexes as you query."
echo "  When prompted in Console, create these indexes:"
echo ""
echo "  products collection:"
echo "    - category + price"
echo "    - category + createdAt"
echo ""
echo "  orders collection:"
echo "    - userId + createdAt"
echo ""
echo "  reviews collection:"
echo "    - productId + createdAt"
echo ""

echo "📚 STEP 4: UNDERSTAND YOUR BACKEND"
echo "─────────────────────────────────────────────────────────────"
echo "  Read these files to understand how it works:"
echo ""
echo "  1. 00_START_HERE.md"
echo "     ↳ Quick overview of what was created"
echo ""
echo "  2. README_FIREBASE.md"
echo "     ↳ Complete setup & API reference"
echo ""
echo "  3. ARCHITECTURE_DIAGRAM.md"
echo "     ↳ Visual diagrams of the system"
echo ""
echo "  4. src/firebase/FIREBASE_GUIDE.md"
echo "     ↳ Deep-dive examples & best practices"
echo ""

echo "💻 STEP 5: USE IN YOUR COMPONENTS"
echo "─────────────────────────────────────────────────────────────"
echo "  Example: Authentication"
echo ""
echo "  import { useAuth } from './hooks/useAuth';"
echo ""
echo "  function LoginPage() {"
echo "    const { login, loading, error } = useAuth();"
echo "    const result = await login(email, password);"
echo "  }"
echo ""
echo "  Example: Data Fetching"
echo ""
echo "  import { useFirestore } from './hooks/useFirestore';"
echo ""
echo "  function ProductList() {"
echo "    const { data: products } = useFirestore('products', [...]);"
echo "  }"
echo ""

echo "✅ STEP 6: TEST YOUR BACKEND"
echo "─────────────────────────────────────────────────────────────"
echo "  Run through this checklist:"
echo ""
echo "  Authentication:"
echo "    ☐ Signup with new email"
echo "    ☐ Login with correct password"
echo "    ☐ Login fails with wrong password"
echo "    ☐ Logout works"
echo "    ☐ User stays logged in after page reload"
echo ""
echo "  Database:"
echo "    ☐ Create a product"
echo "    ☐ Read the product"
echo "    ☐ Update the product"
echo "    ☐ Delete the product"
echo ""
echo "  Real-Time:"
echo "    ☐ Subscribe to product changes"
echo "    ☐ Update product in Firebase Console"
echo "    ☐ Component updates immediately"
echo ""
echo "  Pagination:"
echo "    ☐ Load products (20 per page)"
echo "    ☐ Click 'Load More'"
echo "    ☐ More items load"
echo ""

echo "🚀 STEP 7: DEPLOY TO PRODUCTION"
echo "─────────────────────────────────────────────────────────────"
echo "  Before deploying, verify:"
echo ""
echo "  ☐ All environment variables set in deployment platform"
echo "  ☐ Security rules deployed to Firestore"
echo "  ☐ Composite indexes created (if needed)"
echo "  ☐ No hardcoded secrets in code"
echo "  ☐ Error handling tested"
echo "  ☐ Loading states show properly"
echo ""
echo "  Then:"
echo "    npm run build"
echo "    # Deploy to your hosting platform"
echo ""

echo "📞 REFERENCE GUIDE"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "  Core Services:"
echo "    ├─ authService.js        : Signup, login, logout"
echo "    ├─ firestoreService.js   : CRUD, queries, pagination"
echo "    └─ constants.js          : Validation, utilities"
echo ""
echo "  Custom Hooks:"
echo "    ├─ useAuth.js            : Authentication state"
echo "    └─ useFirestore.js       : Data fetching"
echo ""
echo "  Configuration:"
echo "    ├─ firebaseConfig.js     : Firebase initialization"
echo "    ├─ firebaseRules.txt     : Security rules"
echo "    └─ .env.example          : Environment template"
echo ""
echo "  Documentation:"
echo "    ├─ README_FIREBASE.md    : Complete guide"
echo "    ├─ FIREBASE_GUIDE.md     : Examples & patterns"
echo "    └─ ARCHITECTURE_DIAGRAM.md : Visual diagrams"
echo ""

echo "🎯 QUICK COMMANDS"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "  # Start dev server"
echo "  npm run dev"
echo ""
echo "  # Build for production"
echo "  npm run build"
echo ""
echo "  # Preview production build"
echo "  npm run preview"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  ✅ SETUP COMPLETE!"
echo ""
echo "  Next: Read 00_START_HERE.md for quick overview"
echo "═══════════════════════════════════════════════════════════════"
